app/recipe/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, StringField
from wtforms.validators import DataRequired, Length

class Categoryform(FlaskForm):
    category_name = TextField('name', validators = [DataRequired(),Length(min=6, max=30)])
    category_description = StringField('description', validators = [DataRequired(), Length(min=6, max=500)])
	
class Recipeform(FlaskForm):
    recipe_name = TextField('name', validators = [DataRequired(), Length(min=6, max=30)])
    recipe_description = StringField('description', validators = [DataRequired(), Length(min=6, max=500)])

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, StringField
from wtforms.validators import DataRequired, Email, Length

class Registerform(FlaskForm):
    first_name = TextField('first_name', validators=[DataRequired(), Length(min=1, max=30)])
    last_name = TextField('last_name', validators=[DataRequired(), Length(min=1, max=30)])
    email = StringField('email', validators=[DataRequired(), Email(), Length(min=6, max=60)])
    password = StringField('password', validators=[DataRequired(), Length(min=8, max=60)])

class Loginform(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=60)])
    password = StringField('password', validators=[DataRequired(), Length(min=8, max=60)])
 

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, login_required
from flask_wtf.csrf import CSRFProtect

app = Flask(__name__)

##config##
app = Flask(__name__, instance_relative_config=True)
csrf = CSRFProtect(app)
app.config.from_object('config.Developer')

yummy = SQLAlchemy(app)

#setup login manager
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_message = 'You must be logged in to view this'
login_manager.view='user.login'


from app.user.views import user as user_blueprint
from app.recipe.views import recipe as recipe_blueprint

app.register_blueprint(user_blueprint)
app.register_blueprint(recipe_blueprint)

app/recipe/__init__.py
from flask import Flask, Blueprint

recipe = Blueprint('recipe', __name__, template_folder = 'templates')

from . import views

app/recipe/views.py
from flask import url_for, redirect, flash, render_template, request,session
from . import forms
from app.user.views import all_users
from functools import wraps
#from forms import Categoryform, Recipeform
from . import recipe
from app.user import views


all_recipes = []
def login_required(fx):
    @wraps(fx)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return fx(*args, **kwargs)
        else:
            flash('You need to be logged in')
            return redirect(url_for('user.login'))
    return wrap
 
"""Crud for recipes"""
@recipe.route('/recipe',methods=['GET','POST'])
@login_required
def list_recipes():
    for user in all_users:
        if user['email']==session['current_user']:
            list_recipes = user['recipes']
            return render_template('recipe_dashboard.html',
                           list_recipes = list_recipes, title='Recipes') 
 
@recipe.route('/recipe/add',methods=['GET','POST'])
@login_required
def add_recipe():
    add_recipe = True
    form = forms.Recipeform()
    if request.method == 'POST':
        lname = form.recipe_name.data
        description = form.recipe_description.data
        new_recipe = {'recipe_name':lname, 'description':description}
        for user in all_users:
            if user['email'] == session['current_user']:
                user['recipes'].append(new_recipe)
                flash('Successfully added item')
                return redirect(url_for('recipe.list_recipes'))
    return render_template('add_recipe.html', action="Add",
                           add_recipe=add_recipe, form = form,
                           title="Add Recipe")
	
@recipe.route('/recipe/edit/<string:recipe_name>', methods=['GET','POST'])
@login_required
def edit_recipe(recipe_name):
    add_recipe = False
    form = forms.Recipeform()
    if request.method == 'POST':
        rname = form.recipe_name.data
        description = form.recipe_description.data
        for user in all_users:
            if user['email'] == session['current_user']:
                for recipe in user['recipes']:
                    if recipe['recipe_name']==recipe_name:
                        recipe['recipe_name']=rname
                        recipe['recipe_description']=description
                        count=len(user['recipes'])
                        flash(count)
                        flash('Successfully edited')
                        return redirect(url_for('recipe.list_recipes'))
    return render_template('add_recipe.html', action="Edit",
                                       add_recipe = add_recipe, form=form, title="Edit Recipe")
						   
@recipe.route('/recipe/delete/<string:recipe_name>', methods=['GET', 'POST'])
@login_required
def delete_recipe(recipe_name):
    if request.method == 'POST':
        for user in all_users:
                if user['email'] == session['current_user']:
                    for recipe in user['recipes']:
                        if recipe['recipe_name']==recipe_name:
                            user['recipes'].remove(recipe)
                            flash('Successfully deleted')
                            return redirect(url_for('recipe.list_recipes'))
    return redirect(url_for('recipe.list_recipes'))

app/user/__init__.py
from flask import Flask, Blueprint

user = Blueprint('user', __name__, template_folder = 'templates')

from . import views

__all__ = ['user']

app/user/views.py
from flask import render_template, flash, redirect, url_for, request, Blueprint,session
from . import forms
#from forms import Registerform, Loginform
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash

user = Blueprint('user', __name__, template_folder = 'templates')

all_users=[]

def login_required(fx):
    @wraps(fx)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return fx(*args, **kwargs)
        else:
            flash('You need to be logged in')
            return redirect(url_for('user.login'))
    return wrap

@user.route('/')
def index():
    return redirect(url_for('user.register'))

@user.route('/signup', methods=['GET','POST'])
def register():
    form = forms.Registerform()
    if request.method == 'POST':
        try:
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            password = generate_password_hash(form.password.data)
            user = {
                'first_name':first_name,
                'last_name':last_name,
                'email':email,
                'password':password,
                'recipes':[]

                }
            all_users.append(user)
            flash('Congratulations, login to confirm your account')
            return redirect(url_for('user.login'))
        except:
            flash('Error please try again')
            pass
        return redirect(url_for('user.register'))
    return render_template('register.html', title = 'Signup',
                           form = form)
   
@user.route('/login', methods = ['GET', 'POST'])
def login():
    form = forms.Loginform()
    if request.method == 'POST':
        for user in all_users:
            for key in user.keys():
                if user['email'] == form.email.data:
                    passwordh = user['password']
                    if check_password_hash(passwordh, form.password.data):
                        session['logged_in']=True
                        session['current_user']=form.email.data
                        flash('Welcome')
                        return redirect(url_for('recipe.list_recipes'))
                flash('Wrong email')
                redirect(url_for('user.login'))
    return render_template('login.html', tilte='Login', form = form)

@user.route('/logout', methods = ['GET','POST'])
@login_required
def logout():
    session.pop('logged_in', None)
    session.pop('current_user', None)
    flash('You must login again')
    return redirect(url_for('user.login'))

app/templates/add_category.html
{%extends "base.html"%}
{%block top%}<li><a href="/signup"><span></span> Logout</a></li>{%endblock%}
{%block body%}
<div id="register-form" class="panel panel-default">
    {%if add_category %} 
       <h1>Add Category</h1>
	   <form id="form-style" action="/dashboard/add" method="POST">
	       {{form.csrf_token}}
           <div class="form-group">
                <label for="category_name">Name:</label>
                <input type="text" class="form-control" name="category_name" required placeholder="category name">
           </div>
           <div class="form-group">
                <label for="category_description">Description:</label>
                <input type="text" class="form-control" name="category_description" required placeholder="describe your category here">
           </div>
           <div class="form-group">
                <button type="submit" class="btn btn-default">Submit</button>
           </div>
       </form>
    {%else%}
       <h1>Edit Category</h1>
	   <form id="form-style" action="/dashboard" method="POST">
	       {{form.csrf_token}}
           <div class="form-group">
               <label for="name">Name:</label>
               <input type="text" class="form-control" name="category_name" required placeholder="new category name">
           </div>
           <div class="form-group">
               <label for="description">Description:</label>
               <input type="text" class="form-control" name="category_description" required placeholder="edit your description">
           </div>
           <div class="form-group">
               <button type="submit" class="btn btn-default">Submit</button>
           </div>
       </form>
   {%endif%}
 
</div>
{%endblock%}

app/templates/add_recipe.html
{%extends "base.html"%}
{%block top%}<li><a href="#"><span></span> Logout</a></li>{%endblock%}
{%block body%}
<div id="register-form" class="panel panel-default">
    {%if add_recipe%}
     <h1>Add Recipe</h1>
     <form id="form-style" action="/recipe/add" method="POST">
	 {{form.csrf_token}}
        <div class="form-group">
        <label for="recipe_name">Name:</label>
         <input type="text" class="form-control" name="recipe_name" required>
        </div>
    <div class="form-group">
     <label for="pwd">Description:</label>
     <input type="text" class="form-control" name="description" required>
    </div>
    <div class="form-group">
  <button type="submit" class="btn btn-default">Submit</button>
  </div>
   </form>
    {%else%}
	<h1>Edit Recipe</h1>
     <form id="form-style" action="/recipe/add" method="POST">
	 {{form.csrf_token}}
        <div class="form-group">
        <label for="name">Name:</label>
         <input type="text" class="form-control" name="recipe_name" required>
        </div>
    <div class="form-group">
     <label for="pwd">Description:</label>
     <input type="text" class="form-control" name="recipe_description" required>
    </div>
    <div class="form-group">
  <button type="submit" class="btn btn-default">Submit</button>
  </div>
   </form>
   {%endif%}
	
</div>
{%endblock%}

app/templates/base.html
<!DOCTYPE html >
<html lang="en">
 <head>
 <title>{{title}}</title>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" type="text/css" href="/static/bootstrap.min.css">
 <link rel="stylesheet" href="/static/font-awesome.min.css">
 <link rel="stylesheet" type="text/css" href="/static/styles.css">
 </head>
 <body>
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/signup">Yummy Recipes</a>
    </div>
    
    <ul class="nav navbar-nav navbar-right">
	{%block top%}{%endblock%}

    </ul>
  </div>
 </nav>
 


  
  <div class="intro-header">
   <div class="container" style="min-height:100% width:80%">
	{% with messages = get_flashed_messages() %}
	  {% if messages %}
	    {% for message in messages %}
		  <div class="alert alert-warning alert-dismissible" role="alert">
			{{message}}
		  </div>
		{% endfor %}
	  {% endif %}
	{% endwith %}
  {%block body%}
  {%endblock%}
  </div>
  
 
 </body>
 
</html>

app/templates/category_dashboard.html
{%extends "base.html"%}
{%block top%}<li><a href="/signup"><span></span> Logout</a></li>{%endblock%}
{%block body%}

<div id="register-form" class="panel panel-default">
   {%if list_categories%}
        <div class= "panel panel-heading">
		    <div class="row" >
			    <div class="col-md-8">
                    <h2>Categories</h2>
		        </div>
				<div class="col-md-4">
				    <li><a href="{{url_for('recipe.add_category')}}">Add</a></li>
				</div>
			</div>
        </div>
        {%for category in list_categories%}
            <div class="nav nav-bar">
	        <li><a href="{{url_for('recipe.list_recipes')}}">{{category.category_name}}</a></li>
	        </div>
	    {%endfor%}	
		 <div style="text-align: center">
    {% else %}
        <div style="text-align: center">
            <h3> No categories have been added. </h3>
            <hr class="intro-divider">
    {% endif %}
            <a href="{{ url_for('recipe.add_category') }}" class="btn btn-success btn-lg">
            <i></i>
            Add category
            </a>
        </div>
      </div>
</div>


{%endblock%}

app/templates/login.html
{%extends "base.html"%}
{%block top%}<li><a href="/signup"><span></span> Signup</a></li>{%endblock%}
{%block body%}
<div id="register-form" class="panel panel-default"><h1>Login</h1>
 <form id="form-style" action="/login" method="POST">
    {{form.csrf_token}}
    <div class="form-group">
     <label for="email">Email address:</label>
     <input type="email" class="form-control" name="email" required>
    </div>
    <div class="form-group">
     <label for="pwd">Password:</label>
     <input type="password" class="form-control" name="password" required>
    </div>
    <div class="form-group">
  <button type="submit" class="btn btn-default">Submit</button>
  </div>
</form>
</div>
{%endblock%}

app/templates/recipe_dashboard.html
{%extends "base.html"%}
{%block top%}<li><a href="/logout"><span></span> Logout</a></li>{%endblock%}
{%block body%}
 <div name="recipe-panel" class="panel panel-default">
    {%if list_recipes%}
      <div class="panel-heading">
	      <div class="row">
		      <div class="col-md-9">Recipes
			  </div>
			  
			  <div class="col-md-3"><a href="/recipe/add" class = "btn btn-info" role= "button">Add</a>
			  </div>
		  </div>
	  </div>
    {%for recipe in list_recipes%}	  
      <div class="panel-body">
	      <div class ="row">
		      <div class="col-md-7">{{recipe.recipe_name}}
		      </div>
			  <div class="col-md-2"> <a href="/recipe/edit/<string:recipe_name>" class="btn btn-default" role= "button">Edit</a></div>
			  <div class="col-md-3"><a href="/recipe/delete/<string:recipe_name>" class="btn btn-default" role= "button">Delete</a></div>
	      </div>
      </div>
     {%endfor%}
	 <div style="text-align: center">
    {% else %}
        <div style="text-align: center">
            <h3> No Recipes have been added. </h3>
            <hr class="intro-divider"><a href="{{ url_for('recipe.add_recipe') }}" class="btn btn-success btn-lg">
            <i></i>
            Add
            </a>
    {% endif %}
            
        </div>
      </div>

 </div>

{%endblock%}

app/templates/recipe_description.html
{%extends "base.html"%}
{%block top%}<li><a href="/logout"><span></span> Logout</a></li>{%endblock%}
{%block body%}
 <div name="recipe-panel" class="panel panel-default">
      <div class="panel-heading">
		      <h3>{{recipe.Recipe.name}}
			  </h3> 
	  </div>		  
      <div class="panel-body">
		   <p>{{recipe.Recipe.description}}</p>     
      </div>
 </div>

{%endblock%}

app/templates/register.html
{%extends "base.html"%}
{%block top%}<li><a href="#"><span></span> Login</a></li>{%endblock%}
{%block body%}
<div id="register-form" class="panel panel-default"><p><h1>Register Here!</h1>
 <form id="form-style" action="/signup" method="POST">
    {{form.csrf_token}}
    <div class="form-group">
     <label for="first_name">First name:</label>
     <input type="text" class="form-control" name="first_name" required>
	</div>
	<div class="form-group">
     <label for="last_name">Last name:</label>
     <input type="text" class="form-control" name="last_name" required>
	</div>
    <div class="form-group">
     <label for="email">Email address:</label>
     <input type="email" class="form-control" name="email" required>
    </div>
    <div class="form-group">
     <label for="pwd">Password:</label>
     <input type="password" class="form-control" name="password" required>
    </div>
    <div class="form-group">
  <button type="submit" class="btn btn-default">Submit</button>
  </div>
</form>
</div>
{%endblock%}